"""从教学包中的唯一色板生成静态网页资源；学习时无需运行。"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    theme = json.loads((ROOT / 'src/systems_science/theme.json').read_text(encoding='utf-8'))
    comment = 'Generated by tools/sync_theme.py from src/systems_science/theme.json.'
    css = f'/* {comment} */\n:root {{\n'
    css += ''.join(f'  --{group}-{key}: {value};\n' for group in ('ui', 'data') for key, value in theme[group].items())
    css += '}\n'
    js = f'// {comment}\nexport const theme = ' + json.dumps(theme, indent=2) + ';\n'
    js += 'export const seriesColors = Object.fromEntries(Object.entries(theme.series).map(([name,key]) => [name,theme.data[key]]));\n'
    target = ROOT / 'web/shared'
    for name, text in [('theme.css', css), ('theme.mjs', js)]:
        path = target / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                raise SystemExit(f'{path.relative_to(ROOT)} needs regeneration')
        else:
            target.mkdir(exist_ok=True)
            path.write_text(text, encoding='utf-8')
    print('Shared theme: ' + ('consistent' if args.check else 'generated'))


if __name__ == '__main__':
    main()
